site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

theme:
  name: "material"
  language: "zh"
  feature:
    tabs: true

repo_name: Index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: "https://github.com/abersheeran/index.py/tree/master/docs/"

nav:
  - 介绍: "index.md"
  - 教程:
      - 第一步: "firststep/index.md"
  - Config:
      - 介绍: "config/index.md"
      - 列表: "config/list.md"
  - Application: application.md
  - HTTP: "http.md"
  - WebSocket: "websocket.md"
  - Lifespan: "event.md"
  - Mount: "mount.md"
  - Test: "test.md"
  - Command: "command.md"
  - OpenAPI: "openapi.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra

plugins:
  - search
