site_name: Index.py
site_description: 一个基于 ASGI 协议的异步 Web 框架.

repo_name: Index.py
repo_url: https://github.com/abersheeran/index.py
edit_uri: "https://github.com/abersheeran/index.py/tree/master/docs/"

use_directory_urls: true

theme:
  name: "material"
  language: "zh"
  feature:
    tabs: true

nav:
  - 概览: "index.md"
  - Application: application.md
  - Route: route.md
  - HTTP: "http.md"
  - WebSocket: "websocket.md"
  - Lifespan: "event.md"
  - Middleware: "middleware.md"
  - Command: "command.md"
  - Configuration:
    - Introduction: "config/index.md"
    - Built-in List: "config/list.md"
  - OpenAPI: "openapi.md"
  - Background Task: "background.md"

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra

plugins:
  - search
